#!/bin/bash
# neofetch - MOSS system information tool
# Minimal MOSS-only version

# Gather info
user="${USER:-root}"
host="${HOSTNAME:-moss}"
kernel="MOSS 0.1.0 i686"

# Colors
G='\e[32m'
B='\e[1m'
R='\e[0m'

# Title
echo -e "${G}    .    .   .         .  .${R}       ${B}${G}${user}${R}@${B}${G}${host}${R}"
echo -e "${G}          .  . ...  .   .     .${R}  ----------"
echo -e "${G}          .   ..-*#+:.  .    .  .....${R}  ${B}${G}OS${R}: MOSS 0.1.0"
echo -e "${G} .  .  .   .:=*#######*-. . .      .${R}  ${B}${G}Host${R}: MOSS Virtual Machine"
echo -e "${G} ..  .   :+#######*#######=.  .${R}       ${B}${G}Kernel${R}: ${kernel}"
echo -e "${G}     .:*#######***=***#######=.  .....${R}  ${B}${G}Uptime${R}: unknown"
echo -e "${G}   ..:*#####*****+++*****#####+ .  ..${R}  ${B}${G}Shell${R}: bash"
echo -e "${G}.  ..:*###==**+======++**-+###+     ..${R}  ${B}${G}Terminal${R}: MOSS Console"
echo -e "${G}  . .:*###***===+##*+==+**####+     .${R}  ${B}${G}CPU${R}: i686"
echo -e "${G}     :*###***==+#=:**==+**####+     .${R}  ${B}${G}Memory${R}: ?"
echo -e "${G}     :*###***===*###+==+**####+${R}"
echo -e "${G}..   :*###++*+========+**=*###+.. ....${R}  \e[40m   \e[41m   \e[42m   \e[43m   \e[44m   \e[45m   \e[46m   \e[47m   ${R}"
echo -e "${G}     :*####*****++=+******####+  . ..${R}"
echo -e "${G}.. ...=#######********#######*: ...${R}"
echo -e "${G}  . .   .=#######*+*######*:.        .${R}"
echo -e "${G}. .. .     .-*#########+: .  . ..  .${R}"
echo -e "${G} . . .. .    ..:+###=:.  .  .       ..${R}"
echo -e "${G} .      .      . .       .   .   .   .${R}"
echo -e "${G}          ...   ..     ..  .        .${R}"
